name: Remote State Backend for New TF Organization

on:
  workflow_run:
    workflows: ["Create Terraform Cloud Organization"]
    branches: [main,dev,stage,test]
    types:
      - completed

defaults:
  run:
    working-directory: ./terraform

jobs:
  org_backend:
    name: Create Org Backend
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Statefile Artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{ github.token }}
          workflow: 33272964
          name: terraformstatefile
          path: ./terraform/
          workflow_conclusion: success
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Get current state
        id: current
        continue-on-error: true
        run: |
          if [ -f ./terraform.tfstate.enc ]; then
            echo "Statefile found!"
            openssl enc -d -in ./terraform.tfstate.enc -aes-256-cbc -pbkdf2 -pass pass:"${{ secrets.ENCRYPTION_KEY }}" -out ./terraform.tfstate
          else
            echo "Encrypted statefile not found!"
          fi
      - id: tfbackend
        run: |
          cat <<EOF>> tfbackend.tf
          resource "local_file" "backend" {
            depends_on = [
              module.organization,
              module.oauth_client
            ]
            content = <<-EOT
            workspaces { name = "tfc-org-${module.organization.tfe_organization_id}}
            hostname = "app.terraform.io"
            organization = "${module.organization.tfe_organization_id}"
            EOT
            filename = "${path.module}/config.remote.tfbackend"
          }
          EOF
      - id: remote
        run: |
          cat <<EOF>> remote.tf
          terraform {
            backend "remote" {}
          }
          EOF
      - id: list
        run: ls -lah
